### ISSUE TITLE
License please!

### ISSUE THREAD

**Issue by doismellburning** [jazztpt/NoNullProcess#23]
Thank you, this is awesome! I would love to make liberal use of this please!

I'd be wary of doing that without some sort of "free license" though. I have no particularly strong opinions about what, but as MIT-y as possible would be personally great...!

Cheers

**Comment by epall** [comment]
Thanks for the suggestion, Kristian! Definitely an oversight on our part. Given that this is documentation, not software, I'm not sure what license would be best. What kinds of uses are you thinking of that would warrant a license?

**Comment by doismellburning** [comment]
> Given that this is documentation, not software, I'm not sure what license would be best.

Indeed, I'm afraid I'm not particularly familiar with licenses for the former, but [CC0](https://creativecommons.org/about/cc0) looks most like what I guess I'd prefer.

> What kinds of uses are you thinking of that would warrant a license?

There are definitely environments in which I'd like to copy large chunks of this verbatim; that's well into the territory of "I don't want to do this without explicit permission"!

Cheers

**Comment by epall** [comment]
Gotcha. At least for now, I'd like to maintain attribution, if for nothing else than to encourage upstream contribution. Maybe once we feel like it's more completed we can public-domain it and let folks run wild.
